export const CHECK_ADDRESS = 'CHECK_ADDRESS'
export const USER_INFO = 'USER_INFO'
export const TOKEN_INFO = 'TOKEN_INFO'
export const ADD_ITEM_CARD = 'ADD_ITEM_CARD'
export const LIKE_A_PRODUCT = 'LIKE_A_PRODUCT'
export const MENYER_MAT = 'MENYER_MAT'
export const PLANERA_MAT = 'PLANERA_MAT'